FROM php:7.2-apache

# Enable mod_rewrite for apache
RUN a2enmod rewrite

# Install pdo_pgsql extension for php
RUN apt-get update \
    && apt-get install -y libpq-dev \
    && docker-php-ext-configure pdo_pgsql \
    && docker-php-ext-install pdo_pgsql
