FROM docker.pkg.github.com/jonathanstaniforth/laravel-docker/laravel:v1.3.0

LABEL maintainer="jonathanstaniforth@gmail.com"

# Install pdo_mysql extension for php
RUN docker-php-ext-configure pdo_mysql && docker-php-ext-install pdo_mysql

EXPOSE 80/tcp
EXPOSE 443/tcp
